### ISSUE TITLE
SNYK: Address critical bugs in KServe and TGIS from the scan

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#54]
SNYK scan is complete and we have several critical bugs to address. 
Please see KServe list here:
https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/04393c24-4d2f-40bc-85e5-070e21a5bc74
TGIS has only one: 
https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/4e34f510-1fcc-4f75-ba05-ee8f454f2158

**Comment by israel-hdez** [comment]
TGIS patch: https://github.com/IBM/text-generation-inference/pull/9

**Comment by israel-hdez** [comment]
Those two PRs in the previous ^ comment are the needed changes to move away from any CVE.

TGIS is going to be fully clean

About KServe, the main controller and the qpext are going to be clean. It is important to note that, apparently, Snyk web reports false positives, because of [this](https://docs.snyk.io/scan-application-code/snyk-open-source/starting-to-fix-vulnerabilities/differences-in-vulnerability-counts-across-environments#differences-when-scanning-golang-projects). So, I'm trusting the Snyk CLI which is reporting much smaller list for go-code. Python code still needs to be reviewed, but I'm skipping because I understand ODH is not going to use any python-related assets for now.

I still need to review the results of the _code scan_. This will take some more time, given I'm not familiar with the codebase.

**Comment by israel-hdez** [comment]
ODH cherry-pick of KServe patch: https://github.com/opendatahub-io/kserve/pull/62

**Comment by heyselbi** [comment]
@Xaenalt : critical bugs found by quay are addressed

**Comment by heyselbi** [comment]
https://github.com/red-hat-data-services/kserve/pull/17
https://github.com/red-hat-data-services/kserve/pull/18
https://github.com/red-hat-data-services/odh-manifests/pull/463
https://github.com/red-hat-data-services/odh-manifests/pull/464
